# Generated by Django 5.2.8 on 2025-11-21 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='사건명')),
                ('content', models.TextField(verbose_name='사건 내용')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='AI 분석 결과')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('analyzing', '분석중'), ('analyzed', '분석완료'), ('completed', '완료')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사건',
                'verbose_name_plural': '사건',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='사용자 질문')),
                ('answer', models.TextField(verbose_name='AI 답변')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='출처 판례')),
                ('model', models.CharField(default='', max_length=100, verbose_name='사용 모델')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_histories', to='cases.case', verbose_name='관련 사건')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 히스토리',
                'verbose_name_plural': '채팅 히스토리',
                'db_table': 'chat_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
