# Generated by Django 5.2.8 on 2025-11-25 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0004_add_case_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_histories', to='documents.document', verbose_name='관련 문서'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_histories', to='cases.case', verbose_name='관련 사건 (deprecated)'),
        ),
    ]
