# Generated by Django 5.2.8 on 2025-12-03 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_document_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255, verbose_name='사건명')),
                ('summary', models.TextField(blank=True, verbose_name='사건 요약')),
                ('crime_type', models.CharField(max_length=100, verbose_name='범죄 유형')),
                ('crime_elements', models.JSONField(blank=True, default=dict, verbose_name='구성요건 분석 결과')),
                ('sentencing_factors', models.JSONField(blank=True, default=dict, verbose_name='양형인자')),
                ('expected_sentence', models.JSONField(blank=True, default=dict, verbose_name='예상 양형')),
                ('defense_strategies', models.JSONField(blank=True, default=list, verbose_name='변호 전략')),
                ('related_precedents', models.JSONField(blank=True, default=list, verbose_name='관련 판례')),
                ('stage', models.CharField(choices=[('COMPLAINT', '고소/고발/인지'), ('INVESTIGATION', '수사 진행'), ('PROSECUTION', '기소'), ('TRIAL', '공판'), ('JUDGMENT', '판결'), ('CLOSED', '종결')], default='COMPLAINT', max_length=20, verbose_name='진행 단계')),
                ('schedules', models.JSONField(blank=True, default=list, verbose_name='일정 목록')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='조건 태그')),
                ('uploaded_files', models.JSONField(blank=True, default=list, verbose_name='업로드 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_cases', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '형사 사건',
                'verbose_name_plural': '형사 사건',
                'db_table': 'criminal_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriminalCaseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='일정 날짜')),
                ('title', models.CharField(max_length=255, verbose_name='일정 제목')),
                ('schedule_type', models.CharField(choices=[('HEARING', '공판 기일'), ('SUBMISSION', '서류 제출'), ('MEETING', '상담/회의'), ('DEADLINE', '기한'), ('POLICE', '경찰 출석'), ('PROSECUTOR', '검찰 출석')], max_length=20, verbose_name='일정 유형')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='cases.criminalcase', verbose_name='사건')),
            ],
            options={
                'verbose_name': '형사 사건 일정',
                'verbose_name_plural': '형사 사건 일정',
                'db_table': 'criminal_case_schedules',
                'ordering': ['date'],
            },
        ),
    ]
