# Generated by Django 5.2.8 on 2025-11-21 04:54

from django.db import migrations


def migrate_schema_forward(apps, schema_editor):
    """FastAPI schema → Django schema 변환"""
    with schema_editor.connection.cursor() as cursor:
        # 1. Rename hashed_password → password
        cursor.execute(
            'ALTER TABLE users RENAME COLUMN hashed_password TO password;'
        )

        # 2. Rename created_at → date_joined
        cursor.execute(
            'ALTER TABLE users RENAME COLUMN created_at TO date_joined;'
        )

        # 3. Add missing Django auth fields
        cursor.execute(
            '''
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS is_staff BOOLEAN DEFAULT FALSE,
            ADD COLUMN IF NOT EXISTS is_superuser BOOLEAN DEFAULT FALSE,
            ADD COLUMN IF NOT EXISTS last_login TIMESTAMP NULL;
            '''
        )

        # 4. Drop updated_at (not used in Django)
        cursor.execute(
            'ALTER TABLE users DROP COLUMN IF EXISTS updated_at;'
        )


def migrate_schema_backward(apps, schema_editor):
    """Django schema → FastAPI schema 복원"""
    with schema_editor.connection.cursor() as cursor:
        # Reverse migration
        cursor.execute(
            'ALTER TABLE users RENAME COLUMN password TO hashed_password;'
        )
        cursor.execute(
            'ALTER TABLE users RENAME COLUMN date_joined TO created_at;'
        )
        cursor.execute(
            '''
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            '''
        )
        cursor.execute(
            '''
            ALTER TABLE users
            DROP COLUMN IF EXISTS is_staff,
            DROP COLUMN IF EXISTS is_superuser,
            DROP COLUMN IF EXISTS last_login;
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_schema_forward, migrate_schema_backward),
    ]
