# Generated by Django 5.2.8 on 2025-12-01 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_django_auth_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='검색 쿼리')),
                ('top_k', models.IntegerField(default=3, verbose_name='검색 문서 수')),
                ('response_mode', models.CharField(choices=[('auto', '자동'), ('concise', '간결'), ('standard', '표준'), ('detailed', '상세')], default='auto', max_length=20, verbose_name='응답 모드')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='검색 필터')),
                ('source_count', models.IntegerField(blank=True, null=True, verbose_name='검색 결과 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '검색 기록',
                'verbose_name_plural': '검색 기록',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx')],
            },
        ),
    ]
