# Generated by Django 5.2.8 on 2025-12-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='AI 답변'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사용된 모델'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='revised',
            field=models.BooleanField(default=False, verbose_name='Self-Critique 검증 여부'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='sources',
            field=models.JSONField(blank=True, default=list, verbose_name='참고 자료'),
        ),
    ]
