# Generated by Django 5.2.8 on 2025-11-25 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_migrate_case_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='소스 이름')),
                ('source_type', models.CharField(choices=[('COURT_API', '대법원 판례 API'), ('STATUTE_API', '법령 API'), ('WEB_CRAWL', '웹 크롤링')], max_length=20, verbose_name='소스 유형')),
                ('base_url', models.URLField(max_length=500, verbose_name='기본 URL')),
                ('api_key_required', models.BooleanField(default=False, verbose_name='API 키 필요 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('config', models.JSONField(blank=True, default=dict, help_text='크롤링 관련 추가 설정 (예: 헤더, 쿠키, 페이지네이션 등)', verbose_name='크롤링 설정')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '데이터 소스',
                'verbose_name_plural': '데이터 소스 목록',
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('RUNNING', '실행중'), ('COMPLETED', '완료'), ('FAILED', '실패'), ('CANCELLED', '취소됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('schedule_type', models.CharField(choices=[('MANUAL', '수동'), ('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월')], default='MANUAL', max_length=20, verbose_name='스케줄 유형')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 실행 시간')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='다음 실행 시간')),
                ('documents_collected', models.IntegerField(default=0, verbose_name='수집된 문서 수')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='에러 목록')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='크롤링 필터 (예: start_date, end_date, case_type 등)', verbose_name='필터 조건')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='crawler.datasource', verbose_name='데이터 소스')),
            ],
            options={
                'verbose_name': '크롤링 작업',
                'verbose_name_plural': '크롤링 작업 목록',
                'db_table': 'crawl_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INFO', '정보'), ('SUCCESS', '성공'), ('WARNING', '경고'), ('ERROR', '에러')], default='INFO', max_length=20, verbose_name='상태')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 로그 정보 (예: URL, 응답 코드, 처리 시간 등)', verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_logs', to='crawler.crawljob', verbose_name='크롤링 작업')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_logs', to='documents.document', verbose_name='관련 문서')),
            ],
            options={
                'verbose_name': '크롤링 로그',
                'verbose_name_plural': '크롤링 로그 목록',
                'db_table': 'crawl_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crawl_job', 'status'], name='crawl_logs_crawl_j_77f820_idx'), models.Index(fields=['-created_at'], name='crawl_logs_created_483c47_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status'], name='crawl_jobs_status_d9a592_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['data_source', 'status'], name='crawl_jobs_data_so_e6931b_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-created_at'], name='crawl_jobs_created_1f2652_idx'),
        ),
    ]
