# Generated by Django 5.2.8 on 2025-11-21 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecedentFeedbackStats',
            fields=[
                ('precedent_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='판례 ID')),
                ('total_likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('total_dislikes', models.IntegerField(default=0, verbose_name='싫어요 수')),
                ('total_feedback_count', models.IntegerField(default=0, verbose_name='총 피드백 수')),
                ('like_ratio', models.FloatField(default=0.0, verbose_name='좋아요 비율')),
                ('avg_relevance_score', models.FloatField(blank=True, null=True, verbose_name='평균 관련성 점수')),
                ('should_exclude', models.BooleanField(db_index=True, default=False, verbose_name='검색 결과 제외 여부')),
                ('exclusion_threshold', models.FloatField(default=0.3, verbose_name='제외 임계값')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트 시각')),
            ],
            options={
                'verbose_name': '판례 피드백 통계',
                'verbose_name_plural': '판례 피드백 통계',
                'db_table': 'precedent_feedback_stats',
            },
        ),
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='사건번호')),
                ('title', models.CharField(max_length=500, verbose_name='판례 제목')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='판례 요약')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='판례 전문')),
                ('judgment_summary', models.TextField(blank=True, null=True, verbose_name='판시사항')),
                ('reference_statutes', models.TextField(blank=True, default='[]', verbose_name='참조조문 (JSON 문자열)')),
                ('reference_precedents', models.TextField(blank=True, default='[]', verbose_name='참조판례 (JSON 문자열)')),
                ('precedent_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='대법원 포털 판례 ID')),
                ('court', models.CharField(default='대법원', max_length=100, verbose_name='법원명')),
                ('decision_date', models.DateTimeField(db_index=True, verbose_name='선고일자')),
                ('case_type', models.CharField(default='형사', max_length=50, verbose_name='사건종류')),
                ('specialization_tags', models.TextField(blank=True, default='[]', verbose_name='전문분야 태그 (JSON 문자열)')),
                ('citation', models.CharField(blank=True, max_length=200, null=True, verbose_name='판례 인용 정보')),
                ('case_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='원본 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '판례',
                'verbose_name_plural': '판례',
                'db_table': 'precedents',
                'ordering': ['-decision_date'],
                'indexes': [models.Index(fields=['-decision_date'], name='idx_decision_date_desc'), models.Index(fields=['case_type', '-decision_date'], name='idx_case_type_date')],
            },
        ),
        migrations.CreateModel(
            name='PrecedentFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precedent_id', models.CharField(db_index=True, max_length=200, verbose_name='판례 ID')),
                ('query', models.CharField(max_length=1000, verbose_name='사용자 질의')),
                ('feedback_type', models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=20, verbose_name='피드백 유형')),
                ('is_helpful', models.BooleanField(default=True, verbose_name='도움 여부')),
                ('relevance_score', models.IntegerField(blank=True, null=True, verbose_name='관련성 점수')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='추가 의견')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedent_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '판례 피드백',
                'verbose_name_plural': '판례 피드백',
                'db_table': 'precedent_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
