# Generated by Django 5.2.8 on 2025-11-24 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=255, verbose_name='조직명')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Organization-specific settings (permissions, features, etc.)', verbose_name='설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(help_text='Organization creator (cannot be deleted if organization exists)', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '조직',
                'verbose_name_plural': '조직',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='User role in organization', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='가입일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '멤버십',
                'verbose_name_plural': '멤버십',
                'db_table': 'memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=255, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, help_text='Project description', verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by', '-created_at'], name='organizatio_created_005e17_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', '-joined_at'], name='memberships_organiz_3eadb7_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', '-joined_at'], name='memberships_user_id_76a3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role'], name='memberships_role_9d7025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', '-created_at'], name='projects_organiz_d764bf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', '-created_at'], name='projects_created_fc9bc6_idx'),
        ),
    ]
