# Generated by Django 5.2.8 on 2025-11-24 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title', max_length=500)),
                ('doc_type', models.CharField(choices=[('CASE', 'Case Document'), ('CONTRACT', 'Contract'), ('STATUTE', 'Statute'), ('PRECEDENT', 'Precedent'), ('OTHER', 'Other')], default='OTHER', help_text='Type of document', max_length=20)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'User Upload'), ('CRAWLED', 'Web Crawled'), ('API', 'External API')], default='UPLOAD', help_text='How the document was obtained', max_length=20)),
                ('original_file', models.FileField(blank=True, help_text='Original uploaded file (PDF, DOCX, etc.)', null=True, upload_to='documents/%Y/%m/%d/')),
                ('language', models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='ko', help_text='Document language', max_length=5)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('OCR_DONE', 'OCR Done'), ('PREPROCESSED', 'Preprocessed'), ('EMBEDDED', 'Embedded'), ('FAILED', 'Processing Failed')], db_index=True, default='UPLOADED', help_text='Processing status', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File MIME type (e.g., application/pdf)', max_length=50, null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='Number of pages (for PDFs)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Document owner', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='Sequential index of chunk within document')),
                ('text', models.TextField(help_text='Chunk text content')),
                ('start_offset', models.IntegerField(blank=True, help_text='Starting character position in original document', null=True)),
                ('end_offset', models.IntegerField(blank=True, help_text='Ending character position in original document', null=True)),
                ('page_number', models.IntegerField(blank=True, help_text='Page number (for PDFs)', null=True)),
                ('embedding_id', models.CharField(blank=True, db_index=True, help_text='ID in vector database (ChromaDB/Qdrant)', max_length=255, null=True)),
                ('token_count', models.IntegerField(blank=True, help_text='Approximate token count for this chunk', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='documents_user_id_31091e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'status'], name='documents_doc_typ_724775_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['embedding_id'], name='document_ch_embeddi_2bf246_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
