# Generated by Django 5.2.8 on 2025-11-24 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('PAYMENT', 'Payment Terms'), ('TERMINATION', 'Termination'), ('LIABILITY', 'Liability'), ('CONFIDENTIALITY', 'Confidentiality'), ('DISPUTE', 'Dispute Resolution'), ('WARRANTY', 'Warranty'), ('INDEMNITY', 'Indemnification'), ('FORCE_MAJEURE', 'Force Majeure'), ('INTELLECTUAL_PROPERTY', 'Intellectual Property'), ('OTHER', 'Other')], default='OTHER', help_text='Type of clause', max_length=50)),
                ('title', models.CharField(help_text='Clause title or heading', max_length=500)),
                ('content', models.TextField(help_text='Clause text content')),
                ('importance_score', models.IntegerField(default=50, help_text='Importance score (0-100)')),
                ('llm_model', models.CharField(help_text='LLM model used for extraction', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Associated document', on_delete=django.db.models.deletion.CASCADE, related_name='key_clauses', to='documents.document')),
            ],
            options={
                'db_table': 'key_clauses',
                'ordering': ['-importance_score', '-created_at'],
                'indexes': [models.Index(fields=['document', '-importance_score'], name='key_clauses_documen_875daa_idx'), models.Index(fields=['clause_type'], name='key_clauses_clause__a4300c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('llm_model', models.CharField(help_text='LLM model used for generation (e.g., gpt-4, claude-3-opus)', max_length=100)),
                ('summary_type', models.CharField(choices=[('GLOBAL', 'Global Summary'), ('SECTION', 'Section Summary')], default='GLOBAL', help_text='Type of summary', max_length=20)),
                ('content', models.TextField(help_text='Summary text content')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata (section_title, token_count, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Associated document', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'db_table': 'summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='summaries_documen_04bc27_idx'), models.Index(fields=['summary_type'], name='summaries_summary_86638c_idx')],
            },
        ),
    ]
