# Generated by Django 5.2.8 on 2025-11-25 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_keyclause_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_risk_score', models.IntegerField(default=0, help_text='Overall risk score (0-100, higher is riskier)')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='LOW', help_text='Overall risk severity level', max_length=20)),
                ('risk_items', models.JSONField(default=list, help_text='List of identified risk items with details')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations to mitigate risks')),
                ('summary', models.TextField(help_text='Summary of risk analysis')),
                ('llm_model', models.CharField(help_text='LLM model used for analysis', max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata (token_count, analysis_time, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Associated document', on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='documents.document')),
            ],
            options={
                'db_table': 'risk_analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='risk_analys_documen_f81e9e_idx'), models.Index(fields=['severity', '-overall_risk_score'], name='risk_analys_severit_e0f127_idx')],
            },
        ),
    ]
