# Generated by Django 5.2.8 on 2025-11-25 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_riskanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_case_name', models.CharField(help_text='AI-suggested case name based on content', max_length=255)),
                ('document_types', models.JSONField(default=list, help_text='List of document types identified (e.g., ["판결문", "소장", "계약서"])')),
                ('parties', models.JSONField(default=dict, help_text='Parties involved (e.g., {"원고": "홍길동", "피고": "김철수"})')),
                ('key_dates', models.JSONField(default=dict, help_text='Important dates (e.g., {"사고일": "2024-01-15", "제소일": "2024-02-01"})')),
                ('issues', models.JSONField(default=list, help_text='Key legal issues identified')),
                ('related_precedents', models.JSONField(default=list, help_text='Related precedents from RAG search')),
                ('suggested_next_steps', models.JSONField(default=list, help_text='AI-suggested next steps for the case')),
                ('scenario', models.JSONField(blank=True, default=dict, help_text='Case scenario analysis with confidence scores', null=True)),
                ('llm_model', models.CharField(help_text='LLM model used for analysis', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(help_text='Associated document (must be doc_type=CASE)', on_delete=django.db.models.deletion.CASCADE, related_name='case_analysis', to='documents.document')),
            ],
            options={
                'verbose_name': 'Case Analysis',
                'verbose_name_plural': 'Case Analyses',
                'db_table': 'case_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document'], name='case_analys_documen_b2b5f0_idx'), models.Index(fields=['-created_at'], name='case_analys_created_1c951d_idx')],
            },
        ),
    ]
