# Generated by Django 5.2.8 on 2025-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_migrate_case_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, help_text='File MIME type (e.g., application/pdf)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID in vector database (Qdrant)', max_length=255, null=True),
        ),
    ]
