# Generated by Django 5.2.8 on 2025-12-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_increase_file_type_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analysis_error',
            field=models.TextField(blank=True, help_text='Error message if analysis failed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='analysis_status',
            field=models.CharField(choices=[('none', 'No Analysis'), ('pending', 'Pending'), ('summarizing', 'Summarizing'), ('extracting_clauses', 'Extracting Clauses'), ('analyzing_risk', 'Analyzing Risk'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='none', help_text='Analysis pipeline status', max_length=30),
        ),
    ]
