# Generated by Django 5.2.8 on 2025-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted text content from the document (for original text viewing)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'User Upload'), ('CRAWLED', 'Web Crawled'), ('API', 'External API'), ('AGENT_HUB', 'Agent Hub')], default='UPLOAD', help_text='How the document was obtained', max_length=20),
        ),
    ]
