# Generated by Django 5.2.8 on 2025-11-25 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g., GPT-4 Turbo)', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini'), ('ollama', 'Ollama (Local)')], help_text='LLM provider', max_length=20)),
                ('model_id', models.CharField(help_text='Model ID (e.g., gpt-4-turbo-preview)', max_length=100)),
                ('api_key_env_var', models.CharField(default='LLM_API_KEY', help_text='Environment variable name for API key', max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Custom API endpoint (optional)', null=True)),
                ('default_temperature', models.FloatField(default=0.1)),
                ('default_max_tokens', models.IntegerField(default=2000)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default model for comparison')),
                ('description', models.TextField(blank=True, help_text='Model description and capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model Config',
                'verbose_name_plural': 'LLM Model Configs',
                'db_table': 'llm_model_configs',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMComparisonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(help_text='Comparison session ID')),
                ('task_type', models.CharField(max_length=20)),
                ('input_text', models.TextField(help_text='Original input text')),
                ('results', models.JSONField(default=list, help_text='Array of results from each model')),
                ('total_models', models.IntegerField(default=0)),
                ('fastest_model', models.CharField(blank=True, max_length=100)),
                ('cheapest_model', models.CharField(blank=True, max_length=100)),
                ('preferred_model_id', models.UUIDField(blank=True, help_text="User's preferred model", null=True)),
                ('evaluation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_comparison_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Comparison Result',
                'verbose_name_plural': 'LLM Comparison Results',
                'db_table': 'llm_comparison_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='llm_compari_session_a9d9ff_idx'), models.Index(fields=['user', '-created_at'], name='llm_compari_user_id_62d83c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('summarize', 'Summarize'), ('clauses', 'Extract Clauses'), ('risk_analysis', 'Risk Analysis'), ('case_analysis', 'Case Analysis'), ('compare', 'Model Comparison'), ('chat', 'Chat'), ('other', 'Other')], max_length=20)),
                ('prompt_text', models.TextField(help_text='Input prompt (truncated if too long)')),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of input tokens')),
                ('response_text', models.TextField(blank=True, help_text='LLM response (truncated if too long)')),
                ('response_tokens', models.IntegerField(default=0, help_text='Number of output tokens')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('latency_ms', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
                ('comparison_session_id', models.UUIDField(blank=True, help_text='Session ID for grouped comparisons', null=True)),
                ('document_id', models.UUIDField(blank=True, help_text='Related document ID', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='llm.llmmodelconfig')),
            ],
            options={
                'verbose_name': 'LLM Call Log',
                'verbose_name_plural': 'LLM Call Logs',
                'db_table': 'llm_call_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='llm_call_lo_user_id_f07722_idx'), models.Index(fields=['model_config', '-created_at'], name='llm_call_lo_model_c_3f6de7_idx'), models.Index(fields=['task_type', '-created_at'], name='llm_call_lo_task_ty_f9f381_idx'), models.Index(fields=['comparison_session_id'], name='llm_call_lo_compari_a708d5_idx'), models.Index(fields=['status'], name='llm_call_lo_status_8d4e3f_idx')],
            },
        ),
    ]
