# Generated by Django 5.2.8 on 2025-12-01 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHubSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, help_text='External session identifier', unique=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='세션 제목')),
                ('last_message_preview', models.CharField(blank=True, max_length=500, verbose_name='마지막 메시지 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='메시지 수')),
                ('total_workflows_executed', models.PositiveIntegerField(default=0, verbose_name='워크플로우 실행 수')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 메타데이터')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_hub_sessions', to='organizations.organization', verbose_name='조직')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_hub_sessions', to='organizations.project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_hub_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Agent Hub 세션',
                'verbose_name_plural': 'Agent Hub 세션',
                'db_table': 'agent_hub_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AgentHubMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.agenthubsession', to_field='session_id', verbose_name='세션')),
            ],
            options={
                'verbose_name': 'Agent Hub 메시지',
                'verbose_name_plural': 'Agent Hub 메시지',
                'db_table': 'agent_hub_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agenthubsession',
            index=models.Index(fields=['session_id'], name='agent_hub_s_session_5075fa_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthubsession',
            index=models.Index(fields=['user', '-last_activity'], name='agent_hub_s_user_id_eeda46_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthubsession',
            index=models.Index(fields=['organization', '-last_activity'], name='agent_hub_s_organiz_77609f_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthubmessage',
            index=models.Index(fields=['session', 'created_at'], name='agent_hub_m_session_ec33ee_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthubmessage',
            index=models.Index(fields=['created_at'], name='agent_hub_m_created_698dba_idx'),
        ),
    ]
